import type { Bill, DiscussionPost, ImpactAnalysis } from "./types";

export const MOCK_BILLS: Bill[] = [
  {
    id: "hr-1234",
    billNumber: "H.R. 1234",
    title: "Student Loan Forgiveness and Affordability Act of 2025",
    shortTitle: "Student Loan Forgiveness Act",
    summary:
      "This bill would cancel up to $20,000 in federal student loan debt for borrowers earning under $75,000 annually, expand income-driven repayment options, and cap monthly payments at 5% of discretionary income. It also increases Pell Grant awards by 50% and creates new accountability measures for for-profit colleges.",
    topics: ["education", "finance", "economy"],
    status: "committee",
    chamber: "house",
    sponsor: "Rep. Jamie Foster",
    sponsorParty: "D",
    introducedDate: "2025-01-15",
    lastActionDate: "2025-03-22",
    lastAction: "Referred to House Committee on Education and the Workforce",
    trending: true,
    trendScore: 94,
    tags: ["student loans", "education", "debt relief", "Pell grants"],
  },
  {
    id: "s-567",
    billNumber: "S. 567",
    title: "Affordable Housing Investment and Development Act",
    shortTitle: "Affordable Housing Act",
    summary:
      "Allocates $150 billion over 10 years to build and preserve affordable housing. Creates tax incentives for developers who include affordable units in new construction. Establishes a national renters bill of rights and caps annual rent increases in federally-subsidized buildings at 3% or CPI, whichever is lower.",
    topics: ["housing", "economy", "taxes"],
    status: "introduced",
    chamber: "senate",
    sponsor: "Sen. Maria Reyes",
    sponsorParty: "D",
    introducedDate: "2025-02-08",
    lastActionDate: "2025-04-01",
    lastAction: "Hearing scheduled before Senate Banking Committee",
    trending: true,
    trendScore: 89,
    tags: ["housing", "rent", "affordable housing", "development"],
  },
  {
    id: "hr-2891",
    billNumber: "H.R. 2891",
    title: "Small Business Tax Relief and Investment Act",
    shortTitle: "Small Business Tax Relief Act",
    summary:
      "Provides a 15% tax credit for small businesses with under 50 employees that invest in equipment, technology, or employee training. Raises the small business income threshold for the 20% deduction from $157,000 to $250,000. Simplifies quarterly tax filing for sole proprietors.",
    topics: ["taxes", "small business", "economy"],
    status: "passed_house",
    chamber: "house",
    sponsor: "Rep. David Chen",
    sponsorParty: "R",
    introducedDate: "2024-11-20",
    lastActionDate: "2025-04-10",
    lastAction: "Passed House 287-148, sent to Senate",
    trending: true,
    trendScore: 82,
    tags: ["taxes", "small business", "economy", "entrepreneurship"],
  },
  {
    id: "hr-3301",
    billNumber: "H.R. 3301",
    title: "Expanding Medicare Coverage Act",
    shortTitle: "Medicare Expansion Act",
    summary:
      "Expands Medicare eligibility to individuals aged 55 and older, adds dental and vision coverage for all Medicare beneficiaries, and allows Medicare to negotiate prescription drug prices directly with pharmaceutical companies. Estimated to reduce average out-of-pocket drug costs by 30-50%.",
    topics: ["healthcare", "seniors", "insurance"],
    status: "committee",
    chamber: "house",
    sponsor: "Rep. Sandra Williams",
    sponsorParty: "D",
    introducedDate: "2025-02-28",
    lastActionDate: "2025-04-15",
    lastAction: "Markup session scheduled before House Ways and Means Committee",
    trending: true,
    trendScore: 91,
    tags: ["medicare", "healthcare", "prescription drugs", "seniors"],
  },
  {
    id: "s-789",
    billNumber: "S. 789",
    title: "Clean Energy Jobs and Infrastructure Act",
    shortTitle: "Clean Energy Jobs Act",
    summary:
      "Invests $500 billion over 10 years in clean energy infrastructure including solar, wind, and grid modernization. Creates an estimated 1.5 million clean energy jobs. Provides job retraining programs for fossil fuel workers and establishes a national clean electricity standard requiring 80% clean energy by 2035.",
    topics: ["environment", "energy", "jobs", "climate"],
    status: "introduced",
    chamber: "senate",
    sponsor: "Sen. Alex Johnson",
    sponsorParty: "D",
    introducedDate: "2025-01-30",
    lastActionDate: "2025-03-18",
    lastAction: "Referred to Senate Committee on Energy and Natural Resources",
    trending: false,
    trendScore: 71,
    tags: ["clean energy", "climate", "jobs", "infrastructure"],
  },
  {
    id: "hr-4455",
    billNumber: "H.R. 4455",
    title: "Childcare Access and Workforce Support Act",
    shortTitle: "Childcare Access Act",
    summary:
      "Caps childcare costs at 7% of household income for families earning under $200,000. Invests $75 billion to expand childcare facilities, particularly in underserved communities. Raises minimum wages for childcare workers and creates a new childcare tax credit of up to $3,600 per child under age 6.",
    topics: ["childcare", "families", "economy", "education"],
    status: "committee",
    chamber: "house",
    sponsor: "Rep. Patricia Moore",
    sponsorParty: "D",
    introducedDate: "2025-03-05",
    lastActionDate: "2025-04-20",
    lastAction: "Subcommittee hearing on implementation costs",
    trending: false,
    trendScore: 78,
    tags: ["childcare", "families", "parenting", "workforce"],
  },
  {
    id: "s-1102",
    billNumber: "S. 1102",
    title: "Rural Broadband Expansion and Digital Equity Act",
    shortTitle: "Rural Broadband Act",
    summary:
      "Allocates $65 billion to expand high-speed internet access to unserved and underserved rural and tribal communities. Requires providers to offer affordable service tiers for low-income households. Establishes digital literacy programs and prohibits data throttling for basic educational and government services.",
    topics: ["technology", "rural", "equity"],
    status: "passed_senate",
    chamber: "senate",
    sponsor: "Sen. Robert Kane",
    sponsorParty: "R",
    introducedDate: "2024-10-15",
    lastActionDate: "2025-04-05",
    lastAction: "Passed Senate 68-32, sent to House",
    trending: false,
    trendScore: 65,
    tags: ["broadband", "internet", "rural", "digital equity"],
  },
  {
    id: "hr-5678",
    billNumber: "H.R. 5678",
    title: "Prescription Drug Price Transparency and Fairness Act",
    shortTitle: "Drug Price Transparency Act",
    summary:
      "Requires pharmaceutical companies to justify price increases above 5% annually. Caps out-of-pocket insulin costs at $35/month for all Americans regardless of insurance. Creates a public dashboard showing drug manufacturing costs versus retail prices. Allows importation of FDA-approved drugs from Canada.",
    topics: ["healthcare", "prescription drugs", "transparency"],
    status: "committee",
    chamber: "house",
    sponsor: "Rep. Kevin Marsh",
    sponsorParty: "R",
    introducedDate: "2025-02-14",
    lastActionDate: "2025-04-18",
    lastAction: "Bipartisan support building; 180 cosponsors",
    trending: true,
    trendScore: 88,
    tags: ["drugs", "insulin", "healthcare costs", "transparency"],
  },
];

export const MOCK_DISCUSSION_POSTS: DiscussionPost[] = [
  {
    id: "post-1",
    billId: "hr-1234",
    userId: "user-1",
    displayName: "Sarah M.",
    content:
      "As a first-generation college student with $38k in loans, this would genuinely change my life. I graduated 3 years ago and still can't afford to move out because of monthly payments.",
    type: "opinion",
    upvotes: 247,
    timestamp: "2025-04-20T14:23:00Z",
    aiModerated: true,
  },
  {
    id: "post-2",
    billId: "hr-1234",
    userId: "user-2",
    displayName: "James T.",
    content:
      "Quick question: does this apply to private loans too, or only federal? I have a mix of both from different schools.",
    type: "question",
    upvotes: 89,
    timestamp: "2025-04-20T16:45:00Z",
    aiModerated: true,
  },
  {
    id: "post-3",
    billId: "hr-1234",
    userId: "user-3",
    displayName: "Prof. R. Williams",
    content:
      "The CBO estimates this would cost approximately $400-500 billion over 10 years. Worth noting that the bill only covers federal loans, which represent about 92% of all student debt.",
    type: "fact",
    upvotes: 312,
    timestamp: "2025-04-21T09:12:00Z",
    aiModerated: true,
    sources: ["Congressional Budget Office report, March 2025"],
  },
];

export const MOCK_IMPACT_ANALYSIS: ImpactAnalysis = {
  personalSummary:
    "Based on your profile as a student with federal loans earning under $75,000, this bill could eliminate up to $20,000 of your student debt — potentially your entire balance if it's under that threshold. Your monthly payment would be capped at 5% of your take-home pay, which for your income range means roughly $150-200/month maximum, down from current averages of $300-400. The expanded Pell Grant would benefit current students in your situation, and the income-driven repayment improvements take effect immediately upon passage. However, exact savings depend on your loan type and balance.",
  impactScores: {
    wallet: {
      level: "positive",
      score: 85,
      explanation:
        "If eligible, loan forgiveness directly reduces your debt burden. Payment caps would lower monthly expenses significantly.",
    },
    healthcare: {
      level: "not_directly_affected",
      score: 5,
      explanation: "This bill does not contain provisions that directly affect healthcare coverage or costs.",
    },
    education: {
      level: "positive",
      score: 90,
      explanation:
        "Direct relief on existing loans and stronger Pell Grant funding for current and future students.",
    },
    jobs: {
      level: "mixed",
      score: 45,
      explanation:
        "Could free up income to invest in career development, but economic models vary on broader job market effects.",
    },
    housing: {
      level: "positive",
      score: 60,
      explanation:
        "Reducing monthly debt payments could improve your ability to qualify for housing loans or afford rent.",
    },
    local: {
      level: "mixed",
      score: 40,
      explanation: "Local impact depends on your state's higher education funding relationship with federal programs.",
    },
    rights: {
      level: "not_directly_affected",
      score: 10,
      explanation: "No significant civil rights or legal rights provisions in this bill.",
    },
    environment: {
      level: "not_directly_affected",
      score: 5,
      explanation: "This bill does not address environmental policy.",
    },
  },
  argumentsFor: [
    "Reduces crushing debt burden for millions of graduates, freeing up income for housing, savings, and consumer spending",
    "Addresses systemic inequality — first-generation and low-income students carry disproportionate debt loads",
    "Expanded Pell Grants invest in future workforce development and reduce future borrowing",
    "Income-driven repayment caps prevent financial hardship and reduce default rates",
    "Economic stimulus: freed-up income flows back into local economies",
  ],
  argumentsAgainst: [
    "Estimated cost of $400-500 billion over 10 years adds to the national debt",
    "May be seen as unfair to those who already repaid loans or chose not to attend college",
    "Could incentivize colleges to raise tuition further, knowing debt may be forgiven",
    "Benefits are concentrated among college-educated individuals, not the lowest-income Americans",
    "Does not address the root cause of rising college costs",
  ],
  whoBenefits: [
    "Borrowers with federal student loans under $20,000",
    "Recent graduates earning under $75,000/year",
    "Current students who qualify for expanded Pell Grants",
    "Borrowers on income-driven repayment plans",
    "First-generation college students",
  ],
  whoPays: [
    "Federal taxpayers broadly (CBO estimates $400-500B over 10 years)",
    "Potentially future students if funding is reallocated",
    "Taxpayers who did not attend college or already paid loans",
  ],
  localImpact: [
    "State higher education budgets may be affected by federal funding shifts",
    "Local economies could see increased consumer spending from reduced debt burden",
    "For-profit college accountability measures may close some local campuses",
  ],
  assumptions: [
    "Assumed your loans are federal (not private) based on 'student' role",
    "Income eligibility ($75,000 threshold) based on individual, not household income",
    "Assumed you graduated within the last 10 years based on age range",
    "Implementation timeline assumed to be 12-18 months after signing",
  ],
  confidence: {
    score: 72,
    reason:
      "High confidence on direct financial impact (loan forgiveness amounts are clearly defined). Moderate uncertainty on implementation timeline and potential legal challenges. Bill has not yet passed committee.",
  },
  plainEnglish:
    "Imagine you borrowed money for college and now you owe $20,000. This bill is like the government saying 'we'll pay off up to $20,000 of that for you — if you don't make too much money.' It also makes sure your monthly payments can never be more than 5 cents out of every dollar you earn. Plus, it gives more free money (Pell Grants) to help future students pay for college so they don't have to borrow as much in the first place.",
  questions: [
    "Are your student loans federal or private? Only federal loans are covered.",
    "What is your exact adjusted gross income? The $75,000 threshold determines eligibility.",
    "When did you take out your loans? Timing may affect which forgiveness programs apply.",
  ],
  sources: [
    "H.R. 1234 Bill Text, 119th Congress",
    "Congressional Budget Office Preliminary Score, March 2025",
    "Federal Student Aid Office data on average loan balances",
    "Department of Education income-driven repayment guidelines",
  ],
};
